# basic options
title: PoSHBlog
author: PoSHSauce
email: email@PoSHSauce.com
description: A PoSH site
twitter_username: PoSHSauce
github_username:  PoSHSauce

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
